# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tyKDaGN9N8yRbQqPfqHg2FTZoo_uIAjh
"""

import pandas as pd
from scipy import stats
import numpy as np
df=pd.read_csv("/bmi.csv")
df.head()

df.dropna()

max_val=np.max(np.abs(df[['Height','Weight']]))
max_val

from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
df[['Height','Weight']]=sc.fit_transform(df[['Height','Weight']])
df.head(10)

from sklearn.preprocessing import Normalizer
nm=Normalizer()
df[['Height','Weight']]=nm.fit_transform(df[['Height','Weight']])
df

from sklearn.preprocessing import MaxAbsScaler
mas=MaxAbsScaler()
df[['Height','Weight']]=mas.fit_transform(df[['Height','Weight']])
df

from sklearn.preprocessing import RobustScaler
rs=RobustScaler()
df[['Height','Weight']]=rs.fit_transform(df[['Height','Weight']])
df.head(5)

from scipy.stats import chi2_contingency
import seaborn as sns
tips=sns.load_dataset('tips')
tips.head()

contingency_table=pd.crosstab(tips['sex'],tips['time'])
contingency_table

chi2,p,_,_=chi2_contingency(contingency_table)
print('Chi-square statistic:',chi2)
print('p-value:',p)

from sklearn.feature_selection import SelectKBest,mutual_info_classif,f_classif
data={'Feature1' : [1,2,3,4,5],'Feature2' : ['A','B','C','A','B'],'Feature3' : [0,1,1,0,1],'Target': [0,1,1,0,1]}
df=pd.DataFrame(data)
df

x=df[['Feature1','Feature3']]
y=df['Target']
selector=SelectKBest(score_func=mutual_info_classif,k=1)
x_new=selector.fit_transform(x,y)
print('Selected features:',x_new)

selectedFeatureIndices=selector.get_support(indices=True)
selectedFeatures=x.columns[selectedFeatureIndices]
print('Selected features:',selectedFeatures)

